export const CHANGE_PASSWORD_FORM = [
  {
    name: 'currentPassword',
    label: 'Contraseña Actual',
    type: 'password',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '4',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'newPassword',
    label: 'Nueva Contraseña',
    type: 'password',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '4',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'confirmPassword',
    label: 'Confirmar Contraseña',
    type: 'password',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '4',
    feedback: false,
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    //pattern: /^[a-zA-ZáéíóúÁÉÍÓÜñÜ\s]+$/,
  },
];
