export const CONTRACTOR_FORM = [
  {
    name: 'nom',
    label: 'Nombres',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'ape',
    label: 'Apellidos',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 2,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'numeroDoc',
    label: 'Número de Documento',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '30',
    minLength: '5',
    weight: 3,
    disabled: false,
    placeholder: 'Ingresa tu número de documento',
    pKeyFilter: '[0-9]',
    pattern: '',
  },
  {
    name: 'tipoDoc',
    label: 'Tipo de Documento',
    type: 'select',
    show: true,
    required: true,
    value: '',
    maxLength: '2',
    minLength: '2',
    weight: 4,
    disabled: false,
    placeholder: 'Selecciona tipo de documento',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [
      { label: 'Cédula de Ciudadanía', value: 'cc' },
      { label: 'Cédula de Extranjería', value: 'ce' },
      { label: 'NIT', value: 'nit' },
      { label: 'Pasaporte', value: 'pasaporte' },
      { label: 'Registro Civil', value: 'rc' },
    ],
  },
  {
    name: 'nombreReferente',
    label: 'Nombres Referentes',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '200',
    minLength: '2',
    weight: 5,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'email',
    label: 'Email',
    type: 'email',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 6,
    disabled: false,
    placeholder: 'ejemplo@correo.com',
    pKeyFilter: '',
    pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$',
  },
  {
    name: 'tel',
    label: 'Teléfono',
    type: 'text',
    show: true,
    required: false,
    value: '',
    maxLength: '50',
    minLength: '7',
    weight: 7,
    disabled: false,
    placeholder: '3001234567',
    pKeyFilter: '',
    pattern: '^\\d{7,10}$',
  },
  {
    name: 'celular',
    label: 'Celular',
    type: 'text',
    show: true,
    required: false,
    value: '',
    maxLength: '50',
    minLength: '10',
    weight: 8,
    disabled: false,
    placeholder: '3001234867',
    pKeyFilter: '[0-9]',
    pattern: '^3\\d{9}$',
  },
  {
    name: 'genero',
    label: 'Género',
    type: 'select',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '2',
    weight: 9,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [
      { label: 'Masculino', value: 'masculino' },
      { label: 'Femenino', value: 'femenino' },
      { label: 'Otro', value: 'otro' },
    ],
  },
  {
    name: 'direccion',
    label: 'Dirección',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '255',
    minLength: '2',
    weight: 10,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'ciudad',
    label: 'Ciudad',
    type: 'select',
    show: true,
    required: true,
    value: '',
    maxLength: '120',
    minLength: '2',
    weight: 11,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [
      { label: 'Bogotá D.C.', value: 'bogota' },
      { label: 'Medellín', value: 'medellin' },
      { label: 'Cali', value: 'cali' },
      { label: 'Barranquilla', value: 'barranquilla' },
      { label: 'Cartagena', value: 'cartagena' },
      { label: 'Cúcuta', value: 'cucuta' },
      { label: 'Bucaramanga', value: 'bucaramanga' },
      { label: 'Pereira', value: 'pereira' },
      { label: 'Santa Marta', value: 'santa_marta' },
      { label: 'Ibagué', value: 'ibague' },
      { label: 'Manizales', value: 'manizales' },
      { label: 'Villavicencio', value: 'villavicencio' },
      { label: 'Neiva', value: 'neiva' },
      { label: 'Armenia', value: 'armenia' },
      { label: 'Sincelejo', value: 'sincelejo' },
      { label: 'Popayán', value: 'popayan' },
      { label: 'Valledupar', value: 'valledupar' },
      { label: 'Montería', value: 'monteria' },
      { label: 'Florencia', value: 'florencia' },
      { label: 'Riohacha', value: 'riohacha' },
      { label: 'Tunja', value: 'tunja' },
      { label: 'Yopal', value: 'yopal' },
      { label: 'Mocoa', value: 'mocoa' },
      { label: 'Mitú', value: 'mitu' },
      { label: 'Leticia', value: 'leticia' },
      { label: 'Quibdó', value: 'quibdo' },
      { label: 'Inírida', value: 'inirida' },
      { label: 'San Andrés', value: 'san_andres' },
      { label: 'Pasto', value: 'pasto' },
      { label: 'Puerto Carreño', value: 'puerto_carreno' },
      { label: 'San José del Guaviare', value: 'san_jose_guaviare' },
      { label: 'Bello', value: 'bello' },
      { label: 'Soacha', value: 'soacha' },
      { label: 'Palmira', value: 'palmira' },
      { label: 'Buenaventura', value: 'buenaventura' },
      { label: 'Turbo', value: 'turbo' },
      { label: 'Rionegro', value: 'rionegro' },
      { label: 'Dosquebradas', value: 'dosquebradas' },
      { label: 'Floridablanca', value: 'floridablanca' },
      { label: 'Girón', value: 'giron' },
      { label: 'Piedecuesta', value: 'piedecuesta' },
      { label: 'Soledad', value: 'soledad' },
      { label: 'Malambo', value: 'malambo' },
      { label: 'Barrancabermeja', value: 'barrancabermeja' },
      { label: 'Itagüí', value: 'itagui' },
      { label: 'Envigado', value: 'envigado' },
      { label: 'Tuluá', value: 'tulua' },
      { label: 'Tumaco', value: 'tumaco' },
      { label: 'Maicao', value: 'maicao' },
      { label: 'Ipiales', value: 'ipiales' },
      { label: 'Pitalito', value: 'pitalito' },
      { label: 'Girardot', value: 'girardot' },
      { label: 'Zipaquirá', value: 'zipaquira' },
      { label: 'Chía', value: 'chia' },
      { label: 'Turbaco', value: 'turbaco' },
      { label: 'Arauca', value: 'arauca' },
    ],
  },
  {
    name: 'ciudadExpedicion',
    label: 'Ciudad de Expedición',
    type: 'select',
    show: true,
    required: false,
    value: '',
    maxLength: '120',
    minLength: '2',
    weight: 12,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [
      { label: 'Bogotá D.C.', value: 'bogota' },
      { label: 'Medellín', value: 'medellin' },
      { label: 'Cali', value: 'cali' },
      { label: 'Barranquilla', value: 'barranquilla' },
      { label: 'Cartagena', value: 'cartagena' },
      { label: 'Cúcuta', value: 'cucuta' },
      { label: 'Bucaramanga', value: 'bucaramanga' },
      { label: 'Pereira', value: 'pereira' },
      { label: 'Santa Marta', value: 'santa_marta' },
      { label: 'Ibagué', value: 'ibague' },
      { label: 'Manizales', value: 'manizales' },
      { label: 'Villavicencio', value: 'villavicencio' },
      { label: 'Neiva', value: 'neiva' },
      { label: 'Armenia', value: 'armenia' },
      { label: 'Sincelejo', value: 'sincelejo' },
      { label: 'Popayán', value: 'popayan' },
      { label: 'Valledupar', value: 'valledupar' },
      { label: 'Montería', value: 'monteria' },
      { label: 'Florencia', value: 'florencia' },
      { label: 'Riohacha', value: 'riohacha' },
      { label: 'Tunja', value: 'tunja' },
      { label: 'Yopal', value: 'yopal' },
      { label: 'Mocoa', value: 'mocoa' },
      { label: 'Mitú', value: 'mitu' },
      { label: 'Leticia', value: 'leticia' },
      { label: 'Quibdó', value: 'quibdo' },
      { label: 'Inírida', value: 'inirida' },
      { label: 'San Andrés', value: 'san_andres' },
      { label: 'Pasto', value: 'pasto' },
      { label: 'Puerto Carreño', value: 'puerto_carreno' },
      { label: 'San José del Guaviare', value: 'san_jose_guaviare' },
      { label: 'Bello', value: 'bello' },
      { label: 'Soacha', value: 'soacha' },
      { label: 'Palmira', value: 'palmira' },
      { label: 'Buenaventura', value: 'buenaventura' },
      { label: 'Turbo', value: 'turbo' },
      { label: 'Rionegro', value: 'rionegro' },
      { label: 'Dosquebradas', value: 'dosquebradas' },
      { label: 'Floridablanca', value: 'floridablanca' },
      { label: 'Girón', value: 'giron' },
      { label: 'Piedecuesta', value: 'piedecuesta' },
      { label: 'Soledad', value: 'soledad' },
      { label: 'Malambo', value: 'malambo' },
      { label: 'Barrancabermeja', value: 'barrancabermeja' },
      { label: 'Itagüí', value: 'itagui' },
      { label: 'Envigado', value: 'envigado' },
      { label: 'Tuluá', value: 'tulua' },
      { label: 'Tumaco', value: 'tumaco' },
      { label: 'Maicao', value: 'maicao' },
      { label: 'Ipiales', value: 'ipiales' },
      { label: 'Pitalito', value: 'pitalito' },
      { label: 'Girardot', value: 'girardot' },
      { label: 'Zipaquirá', value: 'zipaquira' },
      { label: 'Chía', value: 'chia' },
      { label: 'Turbaco', value: 'turbaco' },
      { label: 'Arauca', value: 'arauca' },
    ],
  },
  {
    name: 'estado',
    label: 'Estado',
    type: 'select',
    show: true,
    required: true,
    value: 'activo',
    maxLength: '50',
    minLength: '2',
    weight: 13,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [
      { label: 'Activo', value: 'activo' },
      { label: 'Inactivo', value: 'inactivo' },
    ],
  },
  {
    name: 'rol',
    label: 'Rol',
    type: 'select',
    show: true,
    required: true,
    value: 'contratista',
    maxLength: '50',
    minLength: '2',
    weight: 14,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [
      { label: 'Contratista', value: 'contratista' },
      { label: 'Supervisor', value: 'supervisor' },
      { label: 'Administrador', value: 'admin' },
    ],
  },
  {
    name: 'fechaNacimiento',
    label: 'Fecha de Nacimiento',
    type: 'date',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 15,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'contratoVigente',
    label: 'Contrato Vigente',
    type: 'checkbox',
    show: true,
    required: false,
    value: false,
    maxLength: '',
    minLength: '',
    weight: 16,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
];

