export const CONTRACTOR_FORM = [
  {
    name: 'nom',
    label: 'Nombres',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'ape',
    label: 'Apellidos',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 2,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'nombreReferente',
    label: 'Nombres Referentes',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '200',
    minLength: '2',
    weight: 3,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'email',
    label: 'Email',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 4,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'tel',
    label: 'Telefono',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '2',
    weigth: 5,
    disable: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'celular',
    label: 'Celular',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '2',
    weigth: 6,
    disable: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'genero',
    label: 'Genero',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '2',
    weigth: 7,
    disable: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'direccion',
    label: 'Direccion',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '255',
    minLength: '2',
    weight: 8,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'ciudad',
    label: 'Ciudad',
    type: 'text',
    show: true,
    required: false,
    value: '',
    maxLength: '120',
    minLength: '2',
    weight: 9,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'tipoDoc',
    label: 'Tipo de Documento',
    type: 'select',
    show: true,
    required: false,
    value: '',
    maxLength: '120',
    minLength: '2',
    weight: 10,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
    options: [
      {
        label: 'Cedula de Ciudadania',
        value: 'CC',
      },
      {
        label: 'Permiso especial',
        value: 'PE',
      },
      {
        label: 'Pasaporte',
        value: 'PAS',
      },
      {
        label: 'Cedula de Extrangeria',
        value: 'CE',
      },
      {
        label: 'Tarjeta de Identidad',
        value: 'TI',
      },
      {
        label: 'NIT',
        value: 'NIT',
      },
    ],
  },
  {
    name: 'ciudadExpedicion',
    label: 'Ciudad de Expedicion',
    type: 'text',
    show: true,
    required: false,
    value: '',
    maxLength: '120',
    minLength: '2',
    weight: 11,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'estado',
    label: 'Estado',
    type: 'text',
    show: true,
    required: false,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 12,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'rol',
    label: 'Rol',
    type: 'text',
    show: true,
    required: false,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 13,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'fechaNacimiento',
    label: 'Fecha Nacimiento',
    type: 'date',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 14,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'contratoVigente',
    label: 'Contrato Vigente',
    type: 'checkbox',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 15,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  /* {
    name: 'listasChequeo',
    label: 'Listas de Chequeo',
    type: 'checkbox',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 16,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'contratos',
    label: 'Contratos',
    type: 'checkbox',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weigth: 17,
    disable: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'evaluaciones',
    label: 'Evaluaciones',
    type: 'checkbox',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 18,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'periodos',
    label: 'Periodos',
    type: 'checkbox',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 19,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'soportes',
    label: 'Soportes',
    type: 'checkbox',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 20,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  }, */
];
