export const CONTRACTOR_FORM = [
  {
    name: 'nom',
    label: 'Nombres',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'ape',
    label: 'Apellidos',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
];
