export const CONTRACT_FORM = [
  {
    name: 'id',
    label: 'ID',
    type: 'text',
    show: false,
    required: false,
    value: '',
    maxLength: '50',
    minLength: '1',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'numeroContrato',
    label: 'Número de Contrato',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '100',
    minLength: '2',
    weight: 2,
    disabled: false,
    placeholder: 'Digite el número de contrato (único)',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'numeroDocContratista',
    label: 'Contratista',
    type: 'select',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '1',
    weight: 3,
    disabled: false,
    placeholder: 'Seleccione un contratista ACTIVO',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [],
  },
  {
    name: 'idSupervisor',
    label: 'Supervisor',
    type: 'select',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '1',
    weight: 4,
    disabled: false,
    placeholder: 'Seleccione un supervisor ACTIVO',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [],
  },
  {
    name: 'periodoInicio',
    label: 'Periodo Inicio',
    type: 'date',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 5,
    disabled: false,
    placeholder: 'Fecha de inicio del contrato',
    pKeyFilter: '',
    pattern: '',
    dateFormat: 'dd/mm/yy',
  },
  {
    name: 'periodoFin',
    label: 'Periodo Fin',
    type: 'date',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 6,
    disabled: false,
    placeholder: 'Fecha de fin del contrato',
    pKeyFilter: '',
    pattern: '',
    dateFormat: 'dd/mm/yy',
  },
  {
    name: 'valorTotalContrato',
    label: 'Valor Total Contrato',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '1',
    weight: 7,
    disabled: false,
    placeholder: 'Valor total del contrato',
    pKeyFilter: 'num',
    pattern: '^[0-9]+(\\.[0-9]+)?$',
  },
  {
    name: 'numeroPeriodo',
    label: 'Número de Periodos',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '1',
    weight: 8,
    disabled: false,
    placeholder: 'Cantidad de periodos de cobro',
    pKeyFilter: 'num',
    pattern: '^[0-9]+$',
  },
  {
    name: 'valorParaPeriodos',
    label: 'Valor para Periodos',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '1',
    weight: 9,
    disabled: false,
    placeholder: 'Valor distribuido en periodos',
    pKeyFilter: 'num',
    pattern: '^[0-9]+(\\.[0-9]+)?$',
  },
  {
    name: 'estado',
    label: 'Estado',
    type: 'select',
    show: true,
    required: true,
    value: 'vigente',
    maxLength: '20',
    minLength: '1',
    weight: 10,
    disabled: true,
    placeholder: 'Estado del contrato',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [
      { label: 'Vigente', value: 'vigente' },
      { label: 'Prorrogado', value: 'prorrogado' },
      { label: 'Detenido', value: 'detenido' },
      { label: 'Completado', value: 'completado' },
    ],
  },
  {
    name: 'completado',
    label: 'Completado',
    type: 'checkbox',
    show: false,
    required: false,
    value: false,
    maxLength: '',
    minLength: '',
    weight: 11,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'vigente',
    label: 'Vigente',
    type: 'checkbox',
    show: false,
    required: false,
    value: true,
    maxLength: '',
    minLength: '',
    weight: 12,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'prorrogado',
    label: 'Prorrogado',
    type: 'checkbox',
    show: false,
    required: false,
    value: false,
    maxLength: '',
    minLength: '',
    weight: 13,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'detenido',
    label: 'Detenido',
    type: 'checkbox',
    show: false,
    required: false,
    value: false,
    maxLength: '',
    minLength: '',
    weight: 14,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
];

