export const CONTRACTS_FORM = [
  {
    name: 'documentoContratista',
    label: 'Documento De Contratista',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 2,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'anio',
    label: 'Año',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '4',
    minLength: '1',
    weight: 3,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'numeroContrato',
    label: 'Número de Contrato',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '100',
    minLength: '1',
    weight: 4,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'nombreReferente',
    label: 'Nombre Referente',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '200',
    minLength: '1',
    weight: 5,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'cargo',
    label: 'Cargo',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '1',
    weigth: 6,
    disable: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'periodoInicio',
    label: 'Periodo De Inicio',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 7,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'periodoFin',
    label: 'Periodo De Fin',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 8,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'responsableSupervisor',
    label: 'Responsable De Supervisor',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '200',
    minLength: '1',
    weight: 9,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'subsecretarias',
    label: 'SubSecretarias',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 10,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'descripcionObligacion',
    label: 'Descripción De La Obligación',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 11,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'actividadEstrategica',
    label: 'Actividad Estrategica',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 12,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'descripcionMeta',
    label: 'Descripción De La Meta',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 13,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'metaCuantitativa',
    label: 'Meta Cuantitativa',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '100',
    minLength: '3',
    weight: 14,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'unidad',
    label: 'Unidad',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '3',
    weight: 15,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'metaTrimestre',
    label: 'Meta Trimestre',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '100',
    minLength: '3',
    weight: 16,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'metaPorcentajeTrimestre',
    label: 'Meta Porcentaje Trimestre',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '3',
    weight: 17,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'completado',
    label: 'Completado',
    type: 'checkbox',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 18,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'vigente',
    label: 'Vigente',
    type: 'checkbox',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 19,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'prorrogrado',
    label: 'Prorrogrado',
    type: 'checkbox',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 20,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'detenido',
    label: 'Detenido',
    type: 'checkbox',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 21,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'estado',
    label: 'Estado',
    type: 'select',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '3',
    weight: 22,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
    options: [
      {
        label: 'Activo',
        value: 'activo',
      },
      {
        label: 'Inactivo',
        value: 'inactivo',
      },
    ],
  },
  {
    name: 'porcentajeTotal',
    label: 'Porcentaje Total',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '3',
    weight: 23,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'porcentajeRestante',
    label: 'Porcentaje Restante',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '3',
    weight: 24,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'valorTotalContrato',
    label: 'Valor Total Contrato',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '3',
    weight: 25,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'numeroPeriodos',
    label: 'Numero Periodos',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '3',
    weight: 26,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'valorParaPeriodos',
    label: 'Valor para Periodos',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '3',
    weight: 27,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  /*  {
    name: 'fechaCreacion',
    label: 'Fecha Creacion',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 28,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'fechaModificacion',
    label: 'Fecha Modificacion',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 29,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  }, */
  /*   {
    name: 'contratista',
    label: 'Contratista',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 30,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'contratistaId',
    label: 'Contratista Id',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weigth: 31,
    disable: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'tareas',
    label: 'Tareas',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 32,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'evaluaciones',
    label: 'Evaluaciones',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 33,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'periodos',
    label: 'Periodos',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 34,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'objetivos',
    label: 'Objetivos',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 35,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'soportes',
    label: 'Soportes',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 36,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  }, */
];
