export const CONTRACTOR_FORM = [
  {
    name: 'nom',
    label: 'Nombres',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'ape',
    label: 'Apellidos',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 2,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'nombreReferente',
    label: 'Nombres Referentes',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '200',
    minLength: '2',
    weight: 3,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'email',
    label: 'Email',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 4,
    disabled: false,
    placeholder: 'ejemplo@correo.com',
    pKeyFilter: '',
    pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$',
  },
  {
    name: 'tel',
    label: 'Telefono',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 5,
    disabled: false,
    placeholder: '3001234567',
    pKeyFilter: '',
    pattern: '^\\d{7,10}$',
  },
  {
    name: 'celular',
    label: 'Celular',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 6,
    disabled: false,
    placeholder: '3001234867',
    pKeyFilter: '',
    pattern: '^3\\d{9}$',
  },
  {
    name: 'genero',
    label: 'Genero',
    type: 'select',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '2',
    weight: 7,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [
      { label: 'Masculino',
         value: 'masculino' },
      { label: 'Femenino',
         value: 'femenino' },
      { label: 'Otro', 
        value: 'otro' },
  ],

  },
  {
    name: 'direccion',
    label: 'Direccion',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '255',
    minLength: '2',
    weight: 8,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'ciudad',
    label: 'Ciudad',
    type: 'Select',
    show: true,
    required: false,
    value: '',
    maxLength: '120',
    minLength: '2',
    weight: 9,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [
    { label: 'Bogotá D.C.', value: 'bogota' },
    { label: 'Medellín', value: 'medellin' },
    { label: 'Cali', value: 'cali' },
    { label: 'Barranquilla', value: 'barranquilla' },
    { label: 'Cartagena', value: 'cartagena' },
    { label: 'Cúcuta', value: 'cucuta' },
    { label: 'Bucaramanga', value: 'bucaramanga' },
    { label: 'Pereira', value: 'pereira' },
    { label: 'Santa Marta', value: 'santa_marta' },
    { label: 'Ibagué', value: 'ibague' },
    { label: 'Manizales', value: 'manizales' },
    { label: 'Villavicencio', value: 'villavicencio' },
    { label: 'Neiva', value: 'neiva' },
    { label: 'Armenia', value: 'armenia' },
    { label: 'Sincelejo', value: 'sincelejo' },
    { label: 'Popayán', value: 'popayan' },
    { label: 'Valledupar', value: 'valledupar' },
    { label: 'Montería', value: 'monteria' },
    { label: 'Florencia', value: 'florencia' },
    { label: 'Riohacha', value: 'riohacha' },
    { label: 'Tunja', value: 'tunja' },
    { label: 'Yopal', value: 'yopal' },
    { label: 'Mocoa', value: 'mocoa' },
    { label: 'Mitú', value: 'mitu' },
    { label: 'Leticia', value: 'leticia' },
    { label: 'Quibdó', value: 'quibdo' },
    { label: 'Inírida', value: 'inirida' },
    { label: 'San Andrés', value: 'san_andres' },
    { label: 'Pasto', value: 'pasto' },
    { label: 'Puerto Carreño', value: 'puerto_carreno' },
    { label: 'San José del Guaviare', value: 'san_jose_guaviare' },
    { label: 'Bello', value: 'bello' },
    { label: 'Soacha', value: 'soacha' },
    { label: 'Palmira', value: 'palmira' },
    { label: 'Buenaventura', value: 'buenaventura' },
    { label: 'Turbo', value: 'turbo' },
    { label: 'Rionegro', value: 'rionegro' },
    { label: 'Dosquebradas', value: 'dosquebradas' },
    { label: 'Floridablanca', value: 'floridablanca' },
    { label: 'Girón', value: 'giron' },
    { label: 'Piedecuesta', value: 'piedecuesta' },
    { label: 'Soledad', value: 'soledad' },
    { label: 'Malambo', value: 'malambo' },
    { label: 'Barrancabermeja', value: 'barrancabermeja' },
    { label: 'Itagüí', value: 'itagui' },
    { label: 'Envigado', value: 'envigado' },
    { label: 'Tuluá', value: 'tulua' },
    { label: 'Tumaco', value: 'tumaco' },
    { label: 'Maicao', value: 'maicao' },
    { label: 'Ipiales', value: 'ipiales' },
    { label: 'Pitalito', value: 'pitalito' },
    { label: 'Girardot', value: 'girardot' },
    { label: 'Zipaquirá', value: 'zipaquira' },
    { label: 'Chía', value: 'chia' },
    { label: 'Turbaco', value: 'turbaco' },
    { label: 'Arauca', value: 'arauca' },
  ],

  },
  {
  name: 'tipoDoc',
  label: 'Tipo de Documento',
  type: 'select',
  show: true,
  required: true,  
  value: '',
  maxLength: '2',
  minLength: '2',
  weight: 10,
  disabled: false,
  placeholder: 'Selecciona tipo de documento',  
  pKeyFilter: '',
  pattern: '',
  optionName: 'label',
  optionValue: 'value',
  options: [
    
    { label: 'Cédula de Ciudadanía', value: 'cc' },
    { label: 'Cédula de Extranjería', value: 'ce' },
    { label: 'NIT', value: 'nit' },
    { label: 'Pasaporte', value: 'pasaporte' },
    { label: 'Registro Civil', value: 'rc' },
  ],

  },
  {
    name: 'ciudadExpedicion',
    label: 'Ciudad de Expedicion',
    type: 'select',
    show: true,
    required: false,
    value: '',
    maxLength: '120',
    minLength: '2',
    weight: 11,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [ { label: 'Bogotá D.C.', value: 'bogota' },
    { label: 'Medellín', value: 'medellin' },
    { label: 'Cali', value: 'cali' },
    { label: 'Barranquilla', value: 'barranquilla' },
    { label: 'Cartagena', value: 'cartagena' },
    { label: 'Cúcuta', value: 'cucuta' },
    { label: 'Bucaramanga', value: 'bucaramanga' },
    { label: 'Pereira', value: 'pereira' },
    { label: 'Santa Marta', value: 'santa_marta' },
    { label: 'Ibagué', value: 'ibague' },
    { label: 'Manizales', value: 'manizales' },
    { label: 'Villavicencio', value: 'villavicencio' },
    { label: 'Neiva', value: 'neiva' },
    { label: 'Armenia', value: 'armenia' },
    { label: 'Sincelejo', value: 'sincelejo' },
    { label: 'Popayán', value: 'popayan' },
    { label: 'Valledupar', value: 'valledupar' },
    { label: 'Montería', value: 'monteria' },
    { label: 'Florencia', value: 'florencia' },
    { label: 'Riohacha', value: 'riohacha' },
    { label: 'Tunja', value: 'tunja' },
    { label: 'Yopal', value: 'yopal' },
    { label: 'Mocoa', value: 'mocoa' },
    { label: 'Mitú', value: 'mitu' },
    { label: 'Leticia', value: 'leticia' },
    { label: 'Quibdó', value: 'quibdo' },
    { label: 'Inírida', value: 'inirida' },
    { label: 'San Andrés', value: 'san_andres' },
    { label: 'Pasto', value: 'pasto' },
    { label: 'Puerto Carreño', value: 'puerto_carreno' },
    { label: 'San José del Guaviare', value: 'san_jose_guaviare' },
    { label: 'Bello', value: 'bello' },
    { label: 'Soacha', value: 'soacha' },
    { label: 'Palmira', value: 'palmira' },
    { label: 'Buenaventura', value: 'buenaventura' },
    { label: 'Turbo', value: 'turbo' },
    { label: 'Rionegro', value: 'rionegro' },
    { label: 'Dosquebradas', value: 'dosquebradas' },
    { label: 'Floridablanca', value: 'floridablanca' },
    { label: 'Girón', value: 'giron' },
    { label: 'Piedecuesta', value: 'piedecuesta' },
    { label: 'Soledad', value: 'soledad' },
    { label: 'Malambo', value: 'malambo' },
    { label: 'Barrancabermeja', value: 'barrancabermeja' },
    { label: 'Itagüí', value: 'itagui' },
    { label: 'Envigado', value: 'envigado' },
    { label: 'Tuluá', value: 'tulua' },
    { label: 'Tumaco', value: 'tumaco' },
    { label: 'Maicao', value: 'maicao' },
    { label: 'Ipiales', value: 'ipiales' },
    { label: 'Pitalito', value: 'pitalito' },
    { label: 'Girardot', value: 'girardot' },
    { label: 'Zipaquirá', value: 'zipaquira' },
    { label: 'Chía', value: 'chia' },
    { label: 'Turbaco', value: 'turbaco' },
    { label: 'Arauca', value: 'arauca' },
  ],
      
   },
   {
    name: 'estado',
    label: 'Estado',
    type: 'select',
    show: true,
    required: false,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 12,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
    optionName: 'label',
    optionValue: 'value',
    options: [
      { label: 'Activo', value: 'activo' },
      { label: 'Inactivo', value: 'inactivo' },
    ],
  },
  {
    name: 'rol',
    label: 'Rol',
    type: 'text',
    show: true,
    required: false,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 13,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'fechaNacimiento',
    label: 'Fecha Nacimiento',
    type: 'date',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 14,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'contratoVigente',
    label: 'Contrato Vigente',
    type: 'checkbox',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 15,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'listasChequeo',
    label: 'Listas de Chequeo',
    type: 'checkbox',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 16,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'contratos',
    label: 'Contratos',
    type: 'checkbox',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 17,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'evaluaciones',
    label: 'Evaluaciones',
    type: 'checkbox',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 18,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'periodos',
    label: 'Periodos',
    type: 'checkbox',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 19,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'soportes',
    label: 'Soportes',
    type: 'checkbox',
    show: true,
    required: false,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 20,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
];
