export const TASK_FORM = [
  {
    name: 'contrato',
    label: 'Contrato',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 1,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'contratoId',
    label: 'Contrato Id',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 2,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'nombreReferente',
    label: 'Nombre De Referente',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 3,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'responsableSupervisor',
    label: 'Responsable Supervisor',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 4,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'tarea',
    label: 'Tarea',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 5,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'estado',
    label: 'Estado',
    type: 'select',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 6,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
    options: [
      {
        label: 'Activo',
        value: 'activo',
      },
      {
        label: 'Inactivo',
        value: 'inactivo',
      },
    ],
  },
  {
    name: 'subsecretarias',
    label: 'Subsecretarias',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 7,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'dimensiones',
    label: 'Dimensiones',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 8,
    disabled: false,
    placeholder: '',
    pKeyFilter: '', 
    pattern: '',
  },
  {
    name: 'responsable',
    label: 'Responsable',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '2',
    weight: 9,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'fechaInicio',
    label: 'Fecha De Inicio',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 10,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'fechaFinalizacion',
    label: 'Fecha De Finalizacion',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 11,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'evidencia',
    label: 'Evidencia',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 12,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'comuna',
    label: 'Comuna',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '100',
    minLength: '2',
    weight: 13,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'tipoPoblacionImpactada',
    label: 'Tipo De Poblacion Impactada',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '150',
    minLength: '3',
    weight: 14,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'cantidadPoblacionImpactada',
    label: 'Cantidad De Poblacion Impactada',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '50',
    minLength: '2',
    weight: 15,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'diasSemana',
    label: 'Dias De La Semana',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '100',
    minLength: '3',
    weight: 16,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'porcentajeAvanceProgramado',
    label: 'Porcentaje De Avance Programado',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '2',
    weight: 17,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'porcentajeRestante',
    label: 'Porcentaje De Restante',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '2',
    weight: 18,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'completado',
    label: 'Completado',
    type: 'checkbox',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 19,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'porcentajeAvanceAlzanzado',
    label: 'Porcentaje De Avance Alzanzado',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '2',
    weight: 20,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'observaciones',
    label: 'Observaciones',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 21,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'porcentajeAvanceprogramadoAcumulado',
    label: 'Porcentaje De Avance Programado Acumulado',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '2',
    weight: 22,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  {
    name: 'porcentajeAvanceNoAlcanzadoAcumulado',
    label: 'Porcentaje De Avance No Alcanzado Acumulado',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '20',
    minLength: '2',
    weight: 23,
    disabled: false,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  },
  /*   {
    name: 'soportes',
    label: 'Soportes',
    type: 'text',
    show: true,
    required: true,
    value: '',
    maxLength: '',
    minLength: '',
    weight: 24,
    disabled: true,
    placeholder: '',
    pKeyFilter: '',
    pattern: '',
  }, */
];
